version: '3.8'
services:
  app:
    image: skill-front
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./:/usr/src/app
    container_name: skill-front
