export const MAX_SFIA_SKILLS = 20;
export const MAX_SOFT_SKILLS = 3;
export const SFIA_MOST_IMPORTANT_SKILLS = 5;
export const SFIA_IMPORTANT_SKILLS = 5;
export const SFIA_VALUABLE_SKILLS = 5;
export const SFIA_FUTURE_SKILLS = 5;

export const TOTAL_PROGRESS =
  MAX_SOFT_SKILLS +
  MAX_SFIA_SKILLS +
  SFIA_MOST_IMPORTANT_SKILLS +
  SFIA_IMPORTANT_SKILLS +
  SFIA_VALUABLE_SKILLS +
  SFIA_FUTURE_SKILLS;
export const URL = 'skillback.fly.dev';